### ISSUE TITLE
Detect data type and remove old data when necessary

### ISSUE THREAD

**Issue by tewald** [humantech/django-ext_fields#1]
So you don't need to set value to None before changing types.

**Comment by jeanschmidt** [comment]
Hi twald, this is by design. I know that this makes deletion slower, forcing a search in all tables. But it makes a lot of sense. First, the class does not need to keep track of the datatype you are using for each field, because for doing so it will force you to save it somewhere, or in the database or in the code. If it is on the database another table must be created and a load overhead will be needed. If it is on the code (like a dict or something) than this lib becomes pointless. Also it'll prevent you to have two models with different property types (I don't know why someone will actually want to do it, if you are doing it probably there is something wrong with your code design, but anyway). 

There is a plus. I don't think in the update process you should rise a query to search in the database if a old type exists. This can be done if the programmer feels the need to by doing Model.ext_fields = {'my_field: None}, with is quite the same, except you really don't need to do it every time you make a update/insert. As I told you before, you shouldn't use the same ext_field to store different data types, although it is allowed.
